# Generated by Django 5.1.4 on 2025-03-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_blog_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
